job:
  name: ra-aid-eval
  namespace: ra-aid-evals  # Namespace for evaluation jobs
  nodeAffinity:
    zone: us-east-dc-cygnus  # Zone for node scheduling
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  backoffLimit: 2  # Number of retries before considering job as failed
  ttlSecondsAfterFinished: 3600  # Cleanup completed jobs after 1 hour

image:
  # These will be overridden by the actual values from your build
  repository: ra-aid-swe-bench
  tag: latest
  pullPolicy: IfNotPresent

# The following environment variables must be set before running the playbook:
# Required API keys:
# - ANTHROPIC_API_KEY
# - OPENAI_API_KEY
# - TAVILY_API_KEY

# S3 configuration for storing evaluation results
s3:
  enabled: false  # Set to true to enable S3 uploads
  bucket: "my-bucket"  # S3 bucket name
  endpoint_url: "https://s3.us-west-002.backblazeb2.com"  # S3-compatible endpoint URL
  region: "us-west-002"  # S3 region
  path_prefix: "evals"  # Base path prefix for all uploads

  # The following environment variables must be set in secrets when s3.enabled is true:
  # - AWS_ACCESS_KEY_ID
  # - AWS_SECRET_ACCESS_KEY
